[project]
authors = ["Sergio Tessaris <tessaris@inf.unibz.it>"]
channels = ["conda-forge"]
description = "unibz STEM school 2025 on Reinforcement Learning"
name = "stem2025-rl"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
lab = { cmd = ["jupyter", "lab"], depends-on = ["configure"] }

[dependencies]
gymnasium-box2d = ">=1.0.0,<2"
jupyterlab = ">=4.3.5,<5"
pixi-kernel = ">=0.6.1,<0.7"
matplotlib = ">=3.10.0,<4"
